name: Python

on:
  push:
    branches: [ main ]
    paths:
      - python/**
  pull_request:
    branches: [ main ]
    paths:
      - python/**

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Test
      working-directory: ./python
      run: python3 -m unittest -v
